"""Regressions for the defects found by reading the package through in 1.4.0.

Every test here failed before the corresponding fix. They are grouped by what
goes wrong for the user rather than by module, because that is what decides
whether a regression matters: the first group is IPA scoring an analysis on
data that is not what was meant, which is the failure this package exists to
prevent.
"""

import os
import pathlib
import stat
import tempfile

import pandas as pd
import pytest

from ipaapi import _payload, cli, history
from ipaapi.auth import Credentials, TokenCache
from ipaapi.client import (
    looks_like_gateway_timeout,
    looks_like_quota,
    _PLUS_AS_SPACE,
)
from ipaapi.dataset import Dataset, load_table
from ipaapi.errors import IPAError, MappingError
from ipaapi.mapping import ColumnMapping, Measurement, Observation
from ipaapi.models import MeasurementType as MT
from ipaapi.triage import Triage


def frame(**cols):
    return pd.DataFrame(cols, dtype=object)


def one_obs(column, mtype=MT.FOLD_CHANGE, **kw):
    return ColumnMapping(
        "ID", "ensembl", [Observation("o", [Measurement(column, mtype, **kw)])]
    )


def write(text, name="data.txt"):
    tmp = pathlib.Path(tempfile.mkdtemp()) / name
    tmp.write_text(text)
    return tmp


# -- wrong data reaching IPA ------------------------------------------------


@pytest.mark.parametrize("value", ["Inf", "-Inf", "inf"])
def test_infinite_fold_changes_are_refused(value):
    """DESeq2 and edgeR emit Inf where a group has zero counts."""
    f = frame(ID=["a", "b"], FC=["2.5", value])
    with pytest.raises(MappingError, match="infinite"):
        Dataset.from_frame(f, one_obs("FC"), name="d")


@pytest.mark.parametrize("mtype", [MT.RATIO, MT.LOG_RATIO, MT.INTENSITY, MT.OTHER])
def test_no_measurement_type_accepts_infinity(mtype):
    assert not mtype.is_plausible(float("inf"))
    assert not mtype.is_plausible(float("-inf"))


def test_a_text_column_declared_as_fold_change_is_refused():
    """The shape of a --FC that is one column off, pointing at gene symbols."""
    f = frame(ID=["ENSG1", "ENSG2"], Sym=["TP53", "BRCA1"])
    with pytest.raises(MappingError, match="not numbers and not blank"):
        Dataset.from_frame(f, one_obs("Sym"), name="d")


def test_the_whole_column_unreadable_says_so():
    f = frame(ID=["a", "b"], Sym=["TP53", "BRCA1"])
    with pytest.raises(MappingError, match="off by one"):
        Dataset.from_frame(f, one_obs("Sym"), name="d")


def test_excel_artefacts_are_refused():
    f = frame(ID=["a", "b", "c"], FC=["2.0", "#DIV/0!", "1,5"])
    with pytest.raises(MappingError, match="not numbers and not blank"):
        Dataset.from_frame(f, one_obs("FC"), name="d")


def test_blank_cells_are_still_allowed():
    """A missing measurement is honest; only unreadable text is the problem."""
    f = frame(ID=["a", "b", "c"], FC=["2.0", "", "NA"])
    assert Dataset.from_frame(f, one_obs("FC"), name="d")


def test_a_comma_in_a_column_name_does_not_reclassify_a_tsv():
    path = write(
        "Gene ID\tlog2FC, shrunken\tp-value\n"
        "ENSG1\t2.0\t0.01\nENSG2\t-3.0\t0.2\n"
    )
    assert list(load_table(path).columns) == ["Gene ID", "log2FC, shrunken", "p-value"]


def test_a_hash_prefixed_header_is_read_not_rejected():
    path = write("#Gene\tlogFC\tPValue\nTP53\t2.0\t0.01\nBRCA1\t-3.0\t0.2\n")
    assert list(load_table(path).columns) == ["Gene", "logFC", "PValue"]


def test_a_real_comment_line_is_still_diagnosed():
    path = write("# generated by pipeline v3, 2026-08-05\nID\tFC\na\t2.0\nb\t3.0\n")
    with pytest.raises(MappingError, match="--skip-rows"):
        load_table(path)


def test_duplicate_column_labels_are_refused():
    """Repeated labels shift values into the wrong measurement slots."""
    f = pd.DataFrame([[1, 2.0, 9.9, 0.01]], columns=["ID", "FC", "FC", "p"])
    mapping = ColumnMapping(
        "ID", "ensembl",
        [Observation("A", [Measurement("FC", MT.FOLD_CHANGE),
                           Measurement("p", MT.P_VALUE)])],
    )
    with pytest.raises(MappingError, match="more than once in the dataset"):
        mapping.validate(f, check_ranges=False)


@pytest.mark.parametrize("blank", ["-", ".", "", "NA", "null"])
def test_every_blank_spelling_is_sent_as_missing(blank):
    f = frame(ID=["a", "b"], FC=["2.0", blank])
    mapping = one_obs("FC")
    pairs = _payload.build_submission_pairs(f, mapping, "app", "proj", "ds")
    assert [v for k, v in pairs if k == "expvalue"] == ["2.0", "NaN"]


def test_float_typed_identifiers_lose_the_decimal():
    f = pd.DataFrame({"ID": [7157.0, 672.0], "FC": [2.0, 3.0]})
    mapping = ColumnMapping(
        "ID", "entrezgene",
        [Observation("o", [Measurement("FC", MT.FOLD_CHANGE)])],
    )
    pairs = _payload.build_submission_pairs(f, mapping, "app", "proj", "ds")
    assert [v for k, v in pairs if k == "geneid"] == ["7157", "672"]


@pytest.mark.parametrize("value", [0.5, 1.7, -0.3])
def test_gain_loss_is_a_code_not_a_scale(value):
    assert not MT.GAIN_LOSS.is_plausible(value)
    assert not MT.CLASSIFICATION.is_plausible(value)


def test_a_cutoff_keeps_its_precision():
    pairs = _payload.build_submission_pairs(
        frame(ID=["a"], FC=["2.0"]),
        one_obs("FC", cutoff=1234567.0), "app", "proj", "ds",
    )
    assert ("cutoff", "1234567") in pairs


def test_the_fdr_warning_mentions_the_cutoff():
    f = frame(ID=[str(i) for i in range(60)],
              FC=["2.0"] * 60,
              Q=[str(round(0.001 * i, 4)) for i in range(60)])
    mapping = ColumnMapping(
        "ID", "ensembl",
        [Observation("o", [Measurement("FC", MT.FOLD_CHANGE),
                           Measurement("Q", MT.FALSE_DISCOVERY, cutoff=0.05)])],
    )
    notes = "\n".join(Dataset.from_frame(f, mapping, name="d").warnings)
    assert "scale the cutoff with it" in notes


# -- error classification ---------------------------------------------------


@pytest.mark.parametrize("body", [
    "Maximum upload size exceeded.",
    "Observation name length exceeded the maximum permitted.",
    "Request entity too large: size limit reached.",
])
def test_a_limit_that_is_not_the_allowance_is_not_quota(body):
    assert not looks_like_quota(200, body)


@pytest.mark.parametrize("body", [
    "Unable to run analysis: Analysis limit exceeded",
    "Your analysis quota for this period has been used.",
    "No analyses remaining on this licence.",
    "Insufficient credits.",
])
def test_a_real_allowance_message_still_reads_as_quota(body):
    assert looks_like_quota(200, body)


@pytest.mark.parametrize("body", [
    "Unable to run analysis: 504 identifiers could not be mapped.",
    "Your dataset contained 502 genes.",
])
def test_a_bare_number_is_not_a_gateway_timeout(body):
    assert not looks_like_gateway_timeout(200, body)


@pytest.mark.parametrize("body", [
    "504 Gateway Time-out The server didn't respond in time.",
    "502 Bad Gateway",
    "The request timed out.",
])
def test_a_real_timeout_is_still_detected(body):
    assert looks_like_gateway_timeout(200, body)


def test_an_error_page_is_not_reported_as_a_status():
    class Response:
        status_code = 200
        text = "<html><body>currently unavailable</body></html>"

    from ipaapi.client import IPAClient
    client = IPAClient.__new__(IPAClient)
    client._get = lambda *a, **k: Response()
    with pytest.raises(IPAError, match="did not return a status code"):
        client.status("x")


@pytest.mark.parametrize("name,expected", [
    ("NAD+ Signaling", "NAD+ Signaling"),
    ("Ca2+ transport", "Ca2+ transport"),
    ("Acute+Phase+Response", "Acute Phase Response"),
])
def test_entity_names_keep_a_chemical_plus(name, expected):
    assert _PLUS_AS_SPACE.sub(" ", name) == expected


def test_a_caller_session_keeps_its_adapters():
    import requests
    from requests.adapters import HTTPAdapter
    from ipaapi.client import IPAClient

    session = requests.Session()
    mine = HTTPAdapter(pool_maxsize=99)
    session.mount("https://", mine)
    IPAClient(Credentials("t"), session=session)
    assert session.get_adapter("https://x") is mine


# -- names ------------------------------------------------------------------


def test_observation_names_stay_distinct_through_the_final_trim():
    names = [
        "Estrus_vs_2dpp_Immature_cortical_ovarian_stroma_sampleA_Luminal_epithelium_zone",
        "Estrus_vs_2dpp_Immature_cortical_ovarian_stroma_sampleB_Luminal_epithelium_zone",
        "Unrelated_pilot_experiment_from_another_study_entirely_xyz",
    ]
    out = cli.observation_names(names)
    assert len(set(out)) == len(set(names))
    assert all(len(n) <= cli.MAX_OBSERVATION_NAME for n in out)


def test_a_name_is_never_trimmed_to_a_fragment():
    out = cli.observation_names(
        ["EstrusVs2dppImmatureCorticalOvarianStromaTissueSampleAlpha_rep"]
    )
    assert len(out[0].strip("._- ")) >= cli.MIN_STRIPPED_NAME


@pytest.mark.parametrize("token", ["p53", "q30", "fc2", "10", "100"])
def test_an_experimental_variable_is_not_a_cutoff(token):
    assert not cli._is_disposable(token)


@pytest.mark.parametrize("token", ["p0.05", "q0.01", "fdr0.1", "1.5"])
def test_a_real_cutoff_still_reads_as_one(token):
    assert cli._is_disposable(token)


def test_recursive_skips_hidden_directories():
    root = pathlib.Path(tempfile.mkdtemp())
    (root / ".ipynb_checkpoints").mkdir()
    (root / "real.txt").write_text("x")
    (root / ".ipynb_checkpoints" / "real-checkpoint.txt").write_text("x")
    found = cli.discover_files(str(root), None, True)
    assert [p.name for p in found] == ["real.txt"]


# -- durability -------------------------------------------------------------


def test_the_token_cache_is_never_world_readable():
    path = os.path.join(tempfile.mkdtemp(), "token.json")
    TokenCache(path).put("cid", Credentials("secret", refresh_token="rt"))
    mode = stat.S_IMODE(os.stat(path).st_mode)
    assert not mode & (stat.S_IRGRP | stat.S_IROTH)


def test_a_corrupt_expiry_reads_as_a_miss():
    import json
    path = os.path.join(tempfile.mkdtemp(), "token.json")
    with open(path, "w") as fh:
        json.dump({"cid|PythonAPI|analysis.ingenuity.com":
                   {"access_token": "t", "expires_at": "not a number"}}, fh)
    assert TokenCache(path).get("cid", "PythonAPI", "analysis.ingenuity.com") is None


def test_a_non_utf8_byte_does_not_block_submission():
    path = os.path.join(tempfile.mkdtemp(), "log.tsv")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
    with open(path, "ab") as fh:
        fh.write("2026-09-12T10:00:00+00:00\t1\tP\tCaf\xe9\t\t\t\t\n".encode("cp1252"))
    assert cli._already_submitted("P", "anything", path) is None


def test_a_truncated_final_row_is_survivable():
    path = os.path.join(tempfile.mkdtemp(), "log.tsv")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
        fh.write("2026-09-12T10:00:00+00:00\t1\tP\tds\tobs\tsrc\tapp\thost\n")
        fh.write("2026-09-12T10:05:00+00:00\t2\n")
    rows = history.read(path)
    assert all(v is not None for row in rows for v in row.values())


def test_timestamps_sort_chronologically():
    stamps = [history._now() for _ in range(2)]
    assert stamps == sorted(stamps)
    assert stamps[0].endswith("+00:00")


def test_triage_does_not_claim_a_move_that_failed():
    root = pathlib.Path(tempfile.mkdtemp())
    (root / "a.txt").write_text("x")
    os.chmod(root, 0o555)
    try:
        t = Triage(root)
        t.mark_submitted(root / "a.txt")
        assert t.submitted == []
        assert "moved to submitted/" not in t.summary()
    finally:
        os.chmod(root, 0o755)


def test_an_error_note_is_never_picked_up_as_input():
    """The note is output. Re-ingesting one submits it to IPA as a dataset."""
    root = pathlib.Path(tempfile.mkdtemp())
    (root / "run.txt").write_text("ID\tFC\ng1\t2.0\n")
    (root / "run.txt.error.txt").write_text("why it failed last time")
    found = [p.name for p in cli.discover_files(str(root), None, False)]
    assert found == ["run.txt"]


def test_a_note_always_pairs_with_the_file_it_describes():
    """An obviously-named note must not describe a different run."""
    root = pathlib.Path(tempfile.mkdtemp())
    (root / "run.txt").write_text("x")
    Triage(root).mark_failed(root / "run.txt", "reason A")

    # The recovery workflow: pull the file back out, fix the command, re-run.
    (root / "failed" / "run.txt").rename(root / "run.txt")
    Triage(root).mark_failed(root / "run.txt", "reason B")

    notes = sorted(p.name for p in (root / "failed").glob("*.error.txt"))
    assert notes == ["run.txt.error.txt"]
    assert (root / "failed" / "run.txt.error.txt").read_text().strip() == "reason B"


# -- second audit round: defects in the first round of fixes -----------------


@pytest.mark.parametrize("message", [
    "Maximum upload size exceeded",
    "Observation name length exceeded the maximum permitted",
    "Dataset row limit exceeded",
])
def test_a_file_limit_wrapped_in_ipas_own_prefix_is_not_quota(message):
    """Every IPA refusal arrives as 'Unable to run analysis: ...', which used
    to supply the word the allowance gate was looking for."""
    body = f"<html><body>Unable to run analysis: {message}</body></html>"
    assert not looks_like_quota(200, body)


@pytest.mark.parametrize("body,expected", [
    # Prefixed, or followed by the gateway wording: a timeout.
    ("Received HTTP 504 from the upstream server", True),
    ("504 Gateway Time-out The server didn't respond in time.", True),
    ("<html><body><h1>502 Bad Gateway</h1></body></html>", True),
    ("Error 504", True),
    # A bare number is a quantity until something says otherwise. These are all
    # per-file refusals; calling any of them a timeout halts the batch and
    # tells the user their data is fine.
    ("Unable to run analysis: 504 identifiers could not be mapped.", False),
    ("<p>identifiers that could not be mapped: 504.</p>", False),
    ("<p>Maximum number of rows (504) exceeded</p>", False),
    ("<p>Exceeded the maximum number of observations, 504</p>", False),
    ("Rows discarded: 502, kept: 4498", False),
])
def test_timeout_detection_across_real_shapes(body, expected):
    assert looks_like_gateway_timeout(200, body) is expected


@pytest.mark.parametrize("name,expected", [
    ("IL-6+Signaling", "IL-6 Signaling"),
    ("HMGB1+Signaling", "HMGB1 Signaling"),
    ("p38+MAPK+Signaling", "p38 MAPK Signaling"),
    ("NAD+ Signaling", "NAD+ Signaling"),
    ("Ca2+ transport", "Ca2+ transport"),
])
def test_a_digit_before_the_plus_still_decodes(name, expected):
    assert _PLUS_AS_SPACE.sub(" ", name) == expected


def test_a_pandas_na_is_missing_not_unreadable():
    f = pd.DataFrame({"ID": pd.array(["a", "b"], dtype="string"),
                      "FC": pd.array(["2.0", None], dtype="string")})
    dataset = Dataset.from_frame(f, one_obs("FC"), name="d")
    pairs = _payload.build_submission_pairs(f, dataset.mapping, "app", "proj", "ds")
    assert [v for k, v in pairs if k == "expvalue"] == ["2.0", "NaN"]


def test_a_prose_comment_is_still_not_a_header():
    path = write(
        "# DESeq2 results, liver, run 3\n"
        "gene,log2FoldChange,pvalue\nTP53,2.0,0.01\nBRCA1,-3,0.2\n"
    )
    with pytest.raises(MappingError, match="--skip-rows"):
        load_table(path)


def test_blank_lines_above_the_header_do_not_read_as_empty():
    path = write("\n" * 9 + "Gene\tlogFC\nTP53\t2.0\nBRCA1\t-3\n")
    assert list(load_table(path).columns) == ["Gene", "logFC"]


def test_stripping_a_marker_never_invents_a_duplicate():
    path = write("#Gene\tlogFC\tGene\na\t1\tb\nc\t2\td\n")
    with pytest.raises(MappingError, match="header row"):
        load_table(path)


def test_two_files_with_one_stem_are_refused_before_upload():
    """IPA rejects a repeated dataset name, and the stem is the dataset name."""
    root = pathlib.Path(tempfile.mkdtemp())
    for sub in ("groupA", "groupB"):
        (root / sub).mkdir()
        (root / sub / "Sample_DEG.txt").write_text("ID\tFC\ng1\t2.0\n")
    parser = cli.build_parser()
    args = parser.parse_args([
        "submit", str(root), "--project", "P",
        "--ID", "0:ensembl", "--FC", "1:foldchange", "--recursive",
    ])
    with pytest.raises(IPAError, match="same dataset name"):
        cli._load_datasets(args)


def test_the_duplicate_guard_ignores_rows_this_run_wrote():
    rows = [{"project": "P", "dataset_name": "x", "analysis_id": "1"}]
    assert cli._already_submitted("P", "x", None, rows=rows) is not None
    assert cli._already_submitted("P", "y", None, rows=rows) is None


def test_a_trim_that_keeps_only_a_suffix_prefers_the_front():
    for suffix in ("_rep", "_rep1", "_final", "_batch2"):
        name = "HumanLiverCirrhosisVsHealthyControlDifferentialExpression" + suffix
        out = cli.observation_names([name])[0]
        assert out.startswith("HumanLiver"), out
        assert len(out) <= cli.MAX_OBSERVATION_NAME


def test_disambiguation_is_checked_against_every_name_issued():
    base = "HumanLiverCirrhosisVsHealthyControlDiffExpressionCohortTwo"
    names = [base + "_1", base + "_2", base + "_10"]
    out = cli.observation_names(names)
    assert len(set(out)) == 3
    assert all(len(n) <= cli.MAX_OBSERVATION_NAME for n in out)


def test_since_compares_instants_not_strings():
    """A log written before 1.4.0 carries a local offset; one written after
    carries UTC. Compared as text, the older instant sorted later."""
    path = os.path.join(tempfile.mkdtemp(), "log.tsv")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
        fh.write("2026-09-12T23:30:00+02:00\tOLD\tp\tds_old\t\t\t\t\n")  # 21:30Z
        fh.write("2026-09-12T22:00:00+00:00\tNEW\tp\tds_new\t\t\t\t\n")
    rows = history.read(path)
    cutoff = cli._parse_since("2026-09-12T21:45")
    kept = [r["analysis_id"] for r in rows if cli._timestamp_of(r) >= cutoff]
    assert kept == ["NEW"]


def test_an_unreadable_since_is_reported():
    with pytest.raises(IPAError, match="not a date or time"):
        cli._parse_since("yesterday")


def test_a_bom_does_not_blank_every_timestamp():
    path = os.path.join(tempfile.mkdtemp(), "bom.tsv")
    with open(path, "w", encoding="utf-8-sig") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
        fh.write("2026-09-12T22:00:00+00:00\tA1\tp\tds\t\t\t\t\n")
    assert history.read(path)[0]["timestamp"] == "2026-09-12T22:00:00+00:00"


def test_a_cp1252_dataset_name_still_matches_the_guard():
    path = os.path.join(tempfile.mkdtemp(), "cp.tsv")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
    with open(path, "ab") as fh:
        fh.write("2026-09-12T22:00:00+00:00\t1\tP\tM\xfcller_DEG\t\t\t\t\n".encode("cp1252"))
    assert cli._already_submitted("P", "M\xfcller_DEG", path) is not None


def test_a_second_redirect_cannot_replace_a_good_code():
    from ipaapi.auth import _CallbackHandler

    class FakeServer:
        def __init__(self):
            self.result = {"code": "GOOD", "state": "ST", "error": None,
                           "error_description": None}
            self.done = __import__("threading").Event()

    handler = _CallbackHandler.__new__(_CallbackHandler)
    handler.server = FakeServer()
    handler.path = "/?error=access_denied"
    handler.send_response = lambda *a, **k: None
    handler.send_header = lambda *a, **k: None
    handler.end_headers = lambda: None
    handler.wfile = type("W", (), {"write": lambda self, b: None})()
    handler.do_GET()
    assert handler.server.result["code"] == "GOOD"
    assert handler.server.result["error"] is None


def test_forgetting_the_cache_removes_its_lock():
    path = os.path.join(tempfile.mkdtemp(), "token.json")
    cache = TokenCache(path)
    cache.put("cid", Credentials("t"))
    cache.clear()
    assert not os.path.exists(path)
    assert not os.path.exists(path + ".lock")


def test_a_supplied_session_is_used_exactly_as_given():
    """Not replaced, and not mutated either. Two earlier attempts did one or
    the other; a session shared with the caller's own traffic must not silently
    gain retries and backoff."""
    import requests
    from requests.adapters import HTTPAdapter
    from ipaapi.client import IPAClient

    session = requests.Session()
    mine = HTTPAdapter(pool_maxsize=99)
    session.mount("https://", mine)
    before = mine.max_retries
    IPAClient(Credentials("t"), session=session, retries=3)
    assert session.get_adapter("https://x") is mine
    assert mine.max_retries is before


def test_retries_are_configured_on_a_session_we_create():
    from ipaapi.client import IPAClient

    client = IPAClient(Credentials("t"), retries=3)
    assert client.session.get_adapter("https://x").max_retries.total == 3


# -- third audit round -------------------------------------------------------


@pytest.mark.parametrize("body", [
    "<p>identifiers that could not be mapped: 504.</p>",
    "<p>Maximum number of rows (504) exceeded</p>",
    "<p>Exceeded the maximum number of observations, 504</p>",
    "Rows discarded: 502, kept: 4498",
])
def test_a_count_before_punctuation_is_not_a_timeout(body):
    """IPA delivers every error as HTML, so allowing a code before '.', ')' or
    '<' reopened the hole entirely."""
    assert not looks_like_gateway_timeout(200, body)


def test_a_statement_of_allowance_left_is_not_exhaustion():
    assert not looks_like_quota(
        200, "You have 12 analyses remaining in your allowance this month."
    )


def test_allowance_exhausted_still_reads_as_quota():
    assert looks_like_quota(200, "Your allowance has been exhausted.")


def test_a_multi_word_hash_header_is_read():
    """#Gene ID,log2 FC,p value is an ordinary export. Requiring single-token
    field names rejected it, and the advice then destroyed a data row."""
    path = write("#Gene ID,log2 FC,p value\nENSG1,2.0,0.01\nENSG2,-3.0,0.02\n")
    assert list(load_table(path).columns) == ["Gene ID", "log2 FC", "p value"]


def test_strip_does_not_shorten_names_that_already_fit():
    """--strip is a rename, not a licence to run the whole pipeline."""
    names = ["Kidney_KO_vs_WT_results", "Liver_KO_vs_WT_results"]
    assert cli.observation_names(names, strip=["_nomatch"]) == names


def test_strip_still_strips_when_the_names_already_fit():
    """Short names are exactly when --strip is the only way to rename, so
    guarding the strip behind the length check made the flag a silent no-op."""
    names = ["Estrus_vs_2dpp_ovary_paralome_v3", "Diestrus_vs_2dpp_ovary_paralome_v3"]
    assert cli.observation_names(names, strip=["_paralome_v3"]) == [
        "Estrus_vs_2dpp_ovary",
        "Diestrus_vs_2dpp_ovary",
    ]


def test_one_bad_byte_does_not_mojibake_the_whole_log():
    """A log truncated mid-character must not re-read every good row as cp1252
    -- the duplicate guard matches dataset names exactly."""
    path = os.path.join(tempfile.mkdtemp(), "log.tsv")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
        fh.write("2026-09-12T22:00:00+00:00\t1\tP\tMüller_DEG\t\t\t\t\n")
    with open(path, "ab") as fh:
        fh.write(b"2026-09-12T22:01:00+00:00\t2\tP\tSch\xc3\n")
    assert history.read(path)[0]["dataset_name"] == "Müller_DEG"
    assert cli._already_submitted("P", "Müller_DEG", path) is not None


def test_a_matching_state_beats_an_earlier_stale_redirect():
    """A restored tab replaying an old authorization usually arrives FIRST, so
    pure first-wins locked in the stale code and the real one could not correct
    it."""
    import threading
    from ipaapi.auth import _CallbackHandler

    class FakeServer:
        def __init__(self):
            self.result = {}
            self.expected_state = "NEW"
            self.done = threading.Event()

    server = FakeServer()

    def hit(query):
        handler = _CallbackHandler.__new__(_CallbackHandler)
        handler.server = server
        handler.path = query
        handler.send_response = lambda *a, **k: None
        handler.send_header = lambda *a, **k: None
        handler.end_headers = lambda: None
        handler.wfile = type("W", (), {"write": lambda self, b: None})()
        handler.do_GET()

    hit("/?code=STALE&state=OLD")
    hit("/?code=REAL&state=NEW")
    assert server.result["code"] == "REAL"

    # And once the right one has landed, nothing displaces it.
    hit("/?error=access_denied&state=OLD")
    assert server.result["code"] == "REAL"


@pytest.mark.parametrize("name", [
    "QuotaExceededError", "MalformedRequestError", "AnalysisRefusedError",
    "ServiceUnavailableError", "GatewayTimeoutError",
])
def test_the_documented_error_classes_import_from_the_package(name):
    import ipaapi
    assert hasattr(ipaapi, name)
    assert name in ipaapi.__all__


# -- fourth audit round ------------------------------------------------------


@pytest.mark.parametrize("body", [
    "<html><head><title>502 Proxy Error</title></head><body><h1>Proxy Error</h1>"
    "<p>The proxy server received an invalid response from an upstream server.</p></body></html>",
    "ERROR: The requested URL could not be retrieved. Read timeout.",
    "upstream request timeout",
    "An error occurred while processing your request. Reference #97.1f2, Error: 504",
    "The request could not be satisfied. Error from cloudfront",
    "HTTP Error 502.3 - Bad Gateway",
])
def test_real_proxy_pages_are_recognised(body):
    """"Gateway Time-out" and "Bad Gateway" are not the only wordings: Apache
    says proxy error, Squid says read timeout, Envoy says upstream request
    timeout, Akamai says none of them."""
    assert looks_like_gateway_timeout(200, body)


@pytest.mark.parametrize("text,expected", [
    ("#Gene ID,log2 FC,p value\nENSG1,NA,NA\nENSG2,-3.0,0.02\n", ["Gene ID", "log2 FC", "p value"]),
    ("#Gene ID,log2 FC,p value\nENSG1,,\nENSG2,-3.0,0.02\n", ["Gene ID", "log2 FC", "p value"]),
])
def test_a_hash_header_survives_a_blank_first_row(text, expected):
    """A zero-count gene carrying NA everywhere can sort first; it is not
    evidence that the marked line was a comment."""
    assert list(load_table(write(text)).columns) == expected


def test_a_comment_whose_fields_include_a_number_is_still_a_comment():
    """The row below decides, and only that row -- looking further down finds
    the real data and concludes the comment was a header after all."""
    path = write("# DESeq2 results, 24, 48\nGene,t24,t48\nENSG1,2.0,0.01\nENSG2,-3,0.2\n")
    with pytest.raises(MappingError, match="header row"):
        load_table(path)


def test_strip_applies_but_does_not_shorten():
    """Both halves, since guarding on the post-strip names gets one wrong."""
    fits = ["Estrus_vs_2dpp_ovary_paralome_v3", "Diestrus_vs_2dpp_ovary_paralome_v3"]
    assert cli.observation_names(fits, strip=["_paralome_v3"]) == [
        "Estrus_vs_2dpp_ovary", "Diestrus_vs_2dpp_ovary",
    ]
    unchanged = ["Kidney_KO_vs_WT_results", "Liver_KO_vs_WT_results"]
    assert cli.observation_names(unchanged, strip=["_nomatch"]) == unchanged


def test_a_stale_redirect_does_not_wake_login():
    """Waking on any arrival is what made 'matching state wins' unreachable:
    login read the stale state, raised, and closed the port before the genuine
    redirect landed."""
    import threading
    from ipaapi.auth import _CallbackHandler

    class FakeServer:
        def __init__(self):
            self.result = {}
            self.expected_state = "NEW"
            self.done = threading.Event()

    server = FakeServer()

    def hit(query):
        handler = _CallbackHandler.__new__(_CallbackHandler)
        handler.server = server
        handler.path = query
        handler.send_response = lambda *a, **k: None
        handler.send_header = lambda *a, **k: None
        handler.end_headers = lambda: None
        handler.wfile = type("W", (), {"write": lambda self, b: None})()
        handler.do_GET()

    hit("/?code=STALE&state=OLD")
    assert not server.done.is_set()          # login keeps waiting
    hit("/?code=REAL&state=NEW")
    assert server.done.is_set()
    assert server.result["code"] == "REAL"
