"""Regressions for the defects found by reading the package through in 1.4.0.

Every test here failed before the corresponding fix. They are grouped by what
goes wrong for the user rather than by module, because that is what decides
whether a regression matters: the first group is IPA scoring an analysis on
data that is not what was meant, which is the failure this package exists to
prevent.
"""

import os
import pathlib
import stat
import tempfile

import pandas as pd
import pytest

from ipaapi import _payload, cli, history
from ipaapi.auth import Credentials, TokenCache
from ipaapi.client import (
    looks_like_gateway_timeout,
    looks_like_quota,
    _PLUS_AS_SPACE,
)
from ipaapi.dataset import Dataset, load_table
from ipaapi.errors import IPAError, MappingError
from ipaapi.mapping import ColumnMapping, Measurement, Observation
from ipaapi.models import MeasurementType as MT
from ipaapi.triage import Triage


def frame(**cols):
    return pd.DataFrame(cols, dtype=object)


def one_obs(column, mtype=MT.FOLD_CHANGE, **kw):
    return ColumnMapping(
        "ID", "ensembl", [Observation("o", [Measurement(column, mtype, **kw)])]
    )


def write(text, name="data.txt"):
    tmp = pathlib.Path(tempfile.mkdtemp()) / name
    tmp.write_text(text)
    return tmp


# -- wrong data reaching IPA ------------------------------------------------


@pytest.mark.parametrize("value", ["Inf", "-Inf", "inf"])
def test_infinite_fold_changes_are_refused(value):
    """DESeq2 and edgeR emit Inf where a group has zero counts."""
    f = frame(ID=["a", "b"], FC=["2.5", value])
    with pytest.raises(MappingError, match="infinite"):
        Dataset.from_frame(f, one_obs("FC"), name="d")


@pytest.mark.parametrize("mtype", [MT.RATIO, MT.LOG_RATIO, MT.INTENSITY, MT.OTHER])
def test_no_measurement_type_accepts_infinity(mtype):
    assert not mtype.is_plausible(float("inf"))
    assert not mtype.is_plausible(float("-inf"))


def test_a_text_column_declared_as_fold_change_is_refused():
    """The shape of a --FC that is one column off, pointing at gene symbols."""
    f = frame(ID=["ENSG1", "ENSG2"], Sym=["TP53", "BRCA1"])
    with pytest.raises(MappingError, match="not numbers and not blank"):
        Dataset.from_frame(f, one_obs("Sym"), name="d")


def test_the_whole_column_unreadable_says_so():
    f = frame(ID=["a", "b"], Sym=["TP53", "BRCA1"])
    with pytest.raises(MappingError, match="off by one"):
        Dataset.from_frame(f, one_obs("Sym"), name="d")


def test_excel_artefacts_are_refused():
    f = frame(ID=["a", "b", "c"], FC=["2.0", "#DIV/0!", "1,5"])
    with pytest.raises(MappingError, match="not numbers and not blank"):
        Dataset.from_frame(f, one_obs("FC"), name="d")


def test_blank_cells_are_still_allowed():
    """A missing measurement is honest; only unreadable text is the problem."""
    f = frame(ID=["a", "b", "c"], FC=["2.0", "", "NA"])
    assert Dataset.from_frame(f, one_obs("FC"), name="d")


def test_a_comma_in_a_column_name_does_not_reclassify_a_tsv():
    path = write(
        "Gene ID\tlog2FC, shrunken\tp-value\n"
        "ENSG1\t2.0\t0.01\nENSG2\t-3.0\t0.2\n"
    )
    assert list(load_table(path).columns) == ["Gene ID", "log2FC, shrunken", "p-value"]


def test_a_hash_prefixed_header_is_read_not_rejected():
    path = write("#Gene\tlogFC\tPValue\nTP53\t2.0\t0.01\nBRCA1\t-3.0\t0.2\n")
    assert list(load_table(path).columns) == ["Gene", "logFC", "PValue"]


def test_a_real_comment_line_is_still_diagnosed():
    path = write("# generated by pipeline v3, 2026-08-05\nID\tFC\na\t2.0\nb\t3.0\n")
    with pytest.raises(MappingError, match="--skip-rows"):
        load_table(path)


def test_duplicate_column_labels_are_refused():
    """Repeated labels shift values into the wrong measurement slots."""
    f = pd.DataFrame([[1, 2.0, 9.9, 0.01]], columns=["ID", "FC", "FC", "p"])
    mapping = ColumnMapping(
        "ID", "ensembl",
        [Observation("A", [Measurement("FC", MT.FOLD_CHANGE),
                           Measurement("p", MT.P_VALUE)])],
    )
    with pytest.raises(MappingError, match="more than once in the dataset"):
        mapping.validate(f, check_ranges=False)


@pytest.mark.parametrize("blank", ["-", ".", "", "NA", "null"])
def test_every_blank_spelling_is_sent_as_missing(blank):
    f = frame(ID=["a", "b"], FC=["2.0", blank])
    mapping = one_obs("FC")
    pairs = _payload.build_submission_pairs(f, mapping, "app", "proj", "ds")
    assert [v for k, v in pairs if k == "expvalue"] == ["2.0", "NaN"]


def test_float_typed_identifiers_lose_the_decimal():
    f = pd.DataFrame({"ID": [7157.0, 672.0], "FC": [2.0, 3.0]})
    mapping = ColumnMapping(
        "ID", "entrezgene",
        [Observation("o", [Measurement("FC", MT.FOLD_CHANGE)])],
    )
    pairs = _payload.build_submission_pairs(f, mapping, "app", "proj", "ds")
    assert [v for k, v in pairs if k == "geneid"] == ["7157", "672"]


@pytest.mark.parametrize("value", [0.5, 1.7, -0.3])
def test_gain_loss_is_a_code_not_a_scale(value):
    assert not MT.GAIN_LOSS.is_plausible(value)
    assert not MT.CLASSIFICATION.is_plausible(value)


def test_a_cutoff_keeps_its_precision():
    pairs = _payload.build_submission_pairs(
        frame(ID=["a"], FC=["2.0"]),
        one_obs("FC", cutoff=1234567.0), "app", "proj", "ds",
    )
    assert ("cutoff", "1234567") in pairs


def test_the_fdr_warning_mentions_the_cutoff():
    f = frame(ID=[str(i) for i in range(60)],
              FC=["2.0"] * 60,
              Q=[str(round(0.001 * i, 4)) for i in range(60)])
    mapping = ColumnMapping(
        "ID", "ensembl",
        [Observation("o", [Measurement("FC", MT.FOLD_CHANGE),
                           Measurement("Q", MT.FALSE_DISCOVERY, cutoff=0.05)])],
    )
    notes = "\n".join(Dataset.from_frame(f, mapping, name="d").warnings)
    assert "scale the cutoff with it" in notes


# -- error classification ---------------------------------------------------


@pytest.mark.parametrize("body", [
    "Maximum upload size exceeded.",
    "Observation name length exceeded the maximum permitted.",
    "Request entity too large: size limit reached.",
])
def test_a_limit_that_is_not_the_allowance_is_not_quota(body):
    assert not looks_like_quota(200, body)


@pytest.mark.parametrize("body", [
    "Unable to run analysis: Analysis limit exceeded",
    "Your analysis quota for this period has been used.",
    "No analyses remaining on this licence.",
    "Insufficient credits.",
])
def test_a_real_allowance_message_still_reads_as_quota(body):
    assert looks_like_quota(200, body)


@pytest.mark.parametrize("body", [
    "Unable to run analysis: 504 identifiers could not be mapped.",
    "Your dataset contained 502 genes.",
])
def test_a_bare_number_is_not_a_gateway_timeout(body):
    assert not looks_like_gateway_timeout(200, body)


@pytest.mark.parametrize("body", [
    "504 Gateway Time-out The server didn't respond in time.",
    "502 Bad Gateway",
    "The request timed out.",
])
def test_a_real_timeout_is_still_detected(body):
    assert looks_like_gateway_timeout(200, body)


def test_an_error_page_is_not_reported_as_a_status():
    class Response:
        status_code = 200
        text = "<html><body>currently unavailable</body></html>"

    from ipaapi.client import IPAClient
    client = IPAClient.__new__(IPAClient)
    client._get = lambda *a, **k: Response()
    with pytest.raises(IPAError, match="did not return a status code"):
        client.status("x")


@pytest.mark.parametrize("name,expected", [
    ("NAD+ Signaling", "NAD+ Signaling"),
    ("Ca2+ transport", "Ca2+ transport"),
    ("Acute+Phase+Response", "Acute Phase Response"),
])
def test_entity_names_keep_a_chemical_plus(name, expected):
    assert _PLUS_AS_SPACE.sub(" ", name) == expected


def test_a_caller_session_keeps_its_adapters():
    import requests
    from requests.adapters import HTTPAdapter
    from ipaapi.client import IPAClient

    session = requests.Session()
    mine = HTTPAdapter(pool_maxsize=99)
    session.mount("https://", mine)
    IPAClient(Credentials("t"), session=session)
    assert session.get_adapter("https://x") is mine


# -- names ------------------------------------------------------------------


def test_observation_names_stay_distinct_through_the_final_trim():
    names = [
        "Estrus_vs_2dpp_Immature_cortical_ovarian_stroma_sampleA_Luminal_epithelium_zone",
        "Estrus_vs_2dpp_Immature_cortical_ovarian_stroma_sampleB_Luminal_epithelium_zone",
        "Unrelated_pilot_experiment_from_another_study_entirely_xyz",
    ]
    out = cli.observation_names(names)
    assert len(set(out)) == len(set(names))
    assert all(len(n) <= cli.MAX_OBSERVATION_NAME for n in out)


def test_a_name_is_never_trimmed_to_a_fragment():
    out = cli.observation_names(
        ["EstrusVs2dppImmatureCorticalOvarianStromaTissueSampleAlpha_rep"]
    )
    assert len(out[0].strip("._- ")) >= cli.MIN_STRIPPED_NAME


@pytest.mark.parametrize("token", ["p53", "q30", "fc2", "10", "100"])
def test_an_experimental_variable_is_not_a_cutoff(token):
    assert not cli._is_disposable(token)


@pytest.mark.parametrize("token", ["p0.05", "q0.01", "fdr0.1", "1.5"])
def test_a_real_cutoff_still_reads_as_one(token):
    assert cli._is_disposable(token)


def test_recursive_skips_hidden_directories():
    root = pathlib.Path(tempfile.mkdtemp())
    (root / ".ipynb_checkpoints").mkdir()
    (root / "real.txt").write_text("x")
    (root / ".ipynb_checkpoints" / "real-checkpoint.txt").write_text("x")
    found = cli.discover_files(str(root), None, True)
    assert [p.name for p in found] == ["real.txt"]


# -- durability -------------------------------------------------------------


def test_the_token_cache_is_never_world_readable():
    path = os.path.join(tempfile.mkdtemp(), "token.json")
    TokenCache(path).put("cid", Credentials("secret", refresh_token="rt"))
    mode = stat.S_IMODE(os.stat(path).st_mode)
    assert not mode & (stat.S_IRGRP | stat.S_IROTH)


def test_a_corrupt_expiry_reads_as_a_miss():
    import json
    path = os.path.join(tempfile.mkdtemp(), "token.json")
    with open(path, "w") as fh:
        json.dump({"cid|PythonAPI|analysis.ingenuity.com":
                   {"access_token": "t", "expires_at": "not a number"}}, fh)
    assert TokenCache(path).get("cid", "PythonAPI", "analysis.ingenuity.com") is None


def test_a_non_utf8_byte_does_not_block_submission():
    path = os.path.join(tempfile.mkdtemp(), "log.tsv")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
    with open(path, "ab") as fh:
        fh.write("2026-09-12T10:00:00+00:00\t1\tP\tCaf\xe9\t\t\t\t\n".encode("cp1252"))
    assert cli._already_submitted("P", "anything", path) is None


def test_a_truncated_final_row_is_survivable():
    path = os.path.join(tempfile.mkdtemp(), "log.tsv")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\t".join(history.FIELDS) + "\n")
        fh.write("2026-09-12T10:00:00+00:00\t1\tP\tds\tobs\tsrc\tapp\thost\n")
        fh.write("2026-09-12T10:05:00+00:00\t2\n")
    rows = history.read(path)
    assert all(v is not None for row in rows for v in row.values())


def test_timestamps_sort_chronologically():
    stamps = [history._now() for _ in range(2)]
    assert stamps == sorted(stamps)
    assert stamps[0].endswith("+00:00")


def test_triage_does_not_claim_a_move_that_failed():
    root = pathlib.Path(tempfile.mkdtemp())
    (root / "a.txt").write_text("x")
    os.chmod(root, 0o555)
    try:
        t = Triage(root)
        t.mark_submitted(root / "a.txt")
        assert t.submitted == []
        assert "moved to submitted/" not in t.summary()
    finally:
        os.chmod(root, 0o755)


def test_an_error_note_never_overwrites_an_existing_one():
    root = pathlib.Path(tempfile.mkdtemp())
    (root / "run.txt").write_text("x")
    (root / "run.txt.error.txt").write_text("PRECIOUS")
    t = Triage(root)
    t.mark_failed(root / "run.txt.error.txt", "reason A")
    t.mark_failed(root / "run.txt", "reason B")
    assert (root / "failed" / "run.txt.error.txt").read_text() == "PRECIOUS"
