"""Files with a comment or title block above the header row."""

import pathlib
import tempfile

import pytest

from ipaapi.cli import _load_datasets, build_parser
from ipaapi.dataset import load_table
from ipaapi.errors import MappingError

BODY = "EnsemblID\tlog2FC\tpval\nENSG001\t2.4\t0.01\nENSG002\t-3.1\t0.02\n"


def write(text: str) -> pathlib.Path:
    tmp = pathlib.Path(tempfile.mkdtemp()) / "data.txt"
    tmp.write_text(text)
    return tmp


@pytest.fixture
def commented():
    """One comment line above the header."""
    return write("# generated by pipeline v3, 2026-08-05\n" + BODY)


@pytest.fixture
def preamble():
    """Three lines of preamble above the header."""
    return write("# title\n# more notes\n\n" + BODY)


def test_skip_rows_finds_the_header(commented):
    frame = load_table(commented, skip_rows=1)
    assert list(frame.columns) == ["EnsemblID", "log2FC", "pval"]
    assert len(frame) == 2


def test_delimiter_is_sniffed_after_skipping(commented):
    # The comment line contains no tabs; sniffing it would pick the wrong
    # delimiter and collapse the table into a single column.
    frame = load_table(commented, skip_rows=1)
    assert len(frame.columns) == 3


def test_several_preamble_lines(preamble):
    frame = load_table(preamble, skip_rows=3)
    assert list(frame.columns) == ["EnsemblID", "log2FC", "pval"]


def test_unskipped_comment_is_diagnosed_rather_than_silently_wrong(commented):
    with pytest.raises(MappingError, match="--skip-rows"):
        load_table(commented)


def test_skipping_past_the_end_is_reported():
    path = write("# only a comment\n")
    with pytest.raises(MappingError, match="fewer than"):
        load_table(path, skip_rows=5)


def test_negative_skip_rows_rejected(commented):
    with pytest.raises(MappingError, match="cannot be negative"):
        load_table(commented, skip_rows=-1)


def test_column_numbers_count_from_the_header(commented):
    args = build_parser().parse_args(
        [
            "validate",
            str(commented),
            "--skip-rows",
            "1",
            "--ID",
            "0:ensembl",
            "--FC",
            "1:logratio",
        ]
    )
    assert args.skip_rows == 1
    datasets = _load_datasets(args)
    assert datasets[0].mapping.gene_id_column == "EnsemblID"
    assert datasets[0].mapping.observations[0].measurements[0].column == "log2FC"


def test_skip_rows_defaults_to_zero():
    args = build_parser().parse_args(
        ["validate", "f.txt", "--ID", "0:ensembl", "--FC", "1:logratio"]
    )
    assert args.skip_rows == 0
