"""Files with a comment or title block above the header row."""

import pathlib
import tempfile

import pytest

from ipaapi.cli import _load_datasets, build_parser
from ipaapi.dataset import load_table
from ipaapi.errors import MappingError

BODY = "EnsemblID\tlog2FC\tpval\nENSG001\t2.4\t0.01\nENSG002\t-3.1\t0.02\n"


def write(text: str) -> pathlib.Path:
    tmp = pathlib.Path(tempfile.mkdtemp()) / "data.txt"
    tmp.write_text(text)
    return tmp


@pytest.fixture
def commented():
    """One comment line above the header."""
    return write("# generated by pipeline v3, 2026-08-05\n" + BODY)


@pytest.fixture
def preamble():
    """Three lines of preamble above the header."""
    return write("# title\n# more notes\n\n" + BODY)


def test_skip_rows_finds_the_header(commented):
    frame = load_table(commented, skip_rows=1)
    assert list(frame.columns) == ["EnsemblID", "log2FC", "pval"]
    assert len(frame) == 2


def test_delimiter_is_sniffed_after_skipping(commented):
    # The comment line contains no tabs; sniffing it would pick the wrong
    # delimiter and collapse the table into a single column.
    frame = load_table(commented, skip_rows=1)
    assert len(frame.columns) == 3


def test_several_preamble_lines(preamble):
    frame = load_table(preamble, skip_rows=3)
    assert list(frame.columns) == ["EnsemblID", "log2FC", "pval"]


def test_unskipped_comment_is_diagnosed_rather_than_silently_wrong(commented):
    with pytest.raises(MappingError, match="--skip-rows"):
        load_table(commented)


def test_skipping_past_the_end_is_reported():
    path = write("# only a comment\n")
    with pytest.raises(MappingError, match="fewer than"):
        load_table(path, skip_rows=5)


def test_negative_skip_rows_rejected(commented):
    with pytest.raises(MappingError, match="cannot be negative"):
        load_table(commented, skip_rows=-1)


def test_column_numbers_count_from_the_header(commented):
    args = build_parser().parse_args(
        [
            "validate",
            str(commented),
            "--skip-rows",
            "1",
            "--ID",
            "0:ensembl",
            "--FC",
            "1:logratio",
        ]
    )
    assert args.skip_rows == 1
    datasets, problems = _load_datasets(args)
    assert problems == []
    assert datasets[0].mapping.gene_id_column == "EnsemblID"
    assert datasets[0].mapping.observations[0].measurements[0].column == "log2FC"


def test_skip_rows_defaults_to_zero():
    args = build_parser().parse_args(
        ["validate", "f.txt", "--ID", "0:ensembl", "--FC", "1:logratio"]
    )
    assert args.skip_rows == 0


# -- fold change mislabelled as log ratio ----------------------------------


def _dataset(values, mtype):
    import numpy as np
    import pandas as pd

    from ipaapi import ColumnMapping, Dataset, Measurement, Observation

    frame = pd.DataFrame(
        {"id": [f"ENSG{i}" for i in range(len(values))], "fc": values}
    )
    mapping = ColumnMapping(
        "id", "ensembl", [Observation("o", [Measurement("fc", mtype)])]
    )
    return Dataset.from_frame(frame, mapping, name="d", check_ranges=False)


def _distributions():
    import numpy as np

    rng = np.random.default_rng(0)
    ratio = rng.lognormal(0, 1, 500)
    signed = np.where(ratio >= 1, ratio, -1 / ratio)  # ratio, negated below 1
    return signed, np.log2(ratio)


def test_signed_fold_change_declared_as_logratio_is_flagged():
    from ipaapi.models import MeasurementType

    signed, _ = _distributions()
    notes = _dataset(signed, MeasurementType.LOG_RATIO).measurement_warnings
    assert len(notes) == 1
    assert "declare them 'foldchange'" in notes[0]


def test_a_genuine_log_ratio_is_not_flagged():
    from ipaapi.models import MeasurementType

    _, log2 = _distributions()
    assert _dataset(log2, MeasurementType.LOG_RATIO).measurement_warnings == []


def test_fold_change_declared_correctly_is_not_flagged():
    from ipaapi.models import MeasurementType

    signed, _ = _distributions()
    assert _dataset(signed, MeasurementType.FOLD_CHANGE).measurement_warnings == []


def test_small_datasets_are_left_alone():
    """Too few points to say anything about the distribution."""
    from ipaapi.models import MeasurementType

    assert _dataset([2.0, 3.0, -4.0], MeasurementType.LOG_RATIO).measurement_warnings == []
